### PR TITLE
(3) use 'six' for py2/3 compatibility of string types

### PR DESCRIPTION
**Pull request by jquast**
An unused import and some commenting of import groups slipped in.

Closes issue #80.

### CODE REVIEW

**Comment by jquast** [comment]
ping

**Comment by jquast** [comment]
ping

**Comment by jquast** [comment]
I'm folding this into subsequent PR's as documentation and cleanup would cause merge conflicts

**Comment by erikrose** [comment]
Looks fine to me. Merge away! Btw, GH doesn't mail me when you add commits to an existing PR, so it's good that you said "ping".

**Pull request merged**
