### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by gtalarico**
I had the same issue as #144 and felt really dumb after
I think this small snippet could help others avoid the same shame :)

Thank you for this beautiful project!

### CODE REVIEW

**Comment by fwenzel** [comment]
I just saw this, and think it is in line with the rest of the readme, and you're the second person bitten by it so clearly it is an issue. Merging. Thank you!

**Comment by erikrose** [comment]
Thanks, Fred! :-D

**Comment by fwenzel** [comment]
My pleasure! Hope you and yours are doing great!

**Comment by erikrose** [comment]
Likewise!!

**Pull request merged**
