### PR TITLE
blessed-integration: merge to master and release to pypi

### PR DESCRIPTION
**Pull request by jquast**
## final review

**anyone at all**: review `docs/*.rst` and docstrings in `blessings/*.py`: please comment that you have reviewed them even if you do not find errors.
- [x] @jquast: Turn down pylint a bit. It would be nice if we could globally turn off the pylint checks that aren't very accurate or we don't agree with, like all of the ones that currently require noisy "pylint:" pragmas in terminal.py.
- [x] anybody: Sometimes we say `rtype: str`, but it could really return a str _or_ a unicode in Python 2. Maybe we can think of something more accurate to say.
- [ ] @erikrose: final review
  - any further issues or requests: add checkbox items and comment here to notify.
## publish 1.9.5
- [ ] @erikrose merge to master and create release tag https://github.com/erikrose/blessings/releases
- [ ] @erikrose: publish to pypi as wheel package: `python setup.py sdist bdist_wheel upload`

### CODE REVIEW

**Comment by jquast** [comment]
ping

**Comment by erikrose** [comment]
I see it; very exciting. I'll try to clear an evening this week to look over it. Looks like good work!

**Comment by erikrose** [comment]
Made some stylistic improvements (subjective, of course) to contributing.rst as #107. Let me know how that looks to you. If all's well, I'll merge it and make a similar pass over the rest of the docs.

**Comment by erikrose** [comment]
Tests are a big unconventional (#109), though we can fix that later; it needn't block release.

**Comment by jquast** [comment]
I can fix it now. We can remove the custom "develop" all together and just explicitly document the steps for preparing an environment for testing.

**Comment by erikrose** [comment]
Sounds good. But I'd be open to putting things like tox and prospector into tests_require, even though `setup test` wouldn't strictly require them. That would reduce manual involvement.

**Comment by jquast** [comment]
ping

**Comment by erikrose** [comment]
Add a pylint checkbox. It doesn't need to block shipping, but it would be nice. I'll be posting a bunch of docstring wordsmithing soon.

**Comment by jquast** [comment]
regarding,

> anybody: Sometimes we say rtype: str, but it could really return a str or a unicode in Python 2. Maybe we can think of something more accurate to say.

The documentation is published in a python3 environment specifically to address this issue. It is a hyperlink, when clicked, that directs to https://docs.python.org/3/library/stdtypes.html#str to indicate exactly what its type signature is in context of python 3.

**Comment by jquast** [comment]
pylint disabled. the 404 http documentation url checks will pass once the master branch is published.

I do not envision this pull request being merged at this rather dull cadence, and I have many plans to continue contributions. As I do not have pypi permission, I will continue most efforts as the 'blessed' fork, and it too is a "help yourself" repository you may pull features or bug fixes from at your own cadence.

**Comment by dbxnr** [comment]
This seems to have been forgotten about... Worth looking into again @erikrose ?

**Pull request closed without merging**
