### PR TITLE
(4) blessed integration: "Pare down" README.rst, improve sphinx docs

### PR DESCRIPTION
**Pull request by jquast**
Closes issue #78.

This is branched from PR #92 for various author changes to documentation.

- Move and symlink ``README.rst -> docs/intro.rst``.
- split into ``docs/intro.rst``, ``overview.rst``, and ``history.rst``
- fix all ``blessed -> blessings`` references in docs, as well as blessed -> blessings badges and github links.
- use ``:attr:``, ``:meth:``, etc. for all references in ``history.rst``
- polish up the 2.0 release changes documentation
- add ``docs/sphinxext/github.py`` for ``:ghissues:`999``` and similar.
- allow references to python3 api documentation (fe. ``:func:`tty.setraw```).
- added 'docs' build target to ``tox``, which is included as a default target when invoking 'tox'.  "warnings as errors" enabled, so that any issues with the documentation causes a build failure.
- an embarrassing monkeypatch is applied in ``docs/conf.py`` to ensure that "nonlocal image URI found" does not cause a failure ("badges" in README.rst)
- use the ``sphinx_rtd_theme`` so that locally generated documentation matches our target.

Please note that the TeamCity builds fail until acceptance of PR #91.

### CODE REVIEW

**Comment by jquast** [comment]
I haven't got much of a choice but to build PR's ontop of PR's for such cases, expect them.

**Comment by jquast** [comment]
I'm holding back pull requests because of the delay of its dependent PR's such as this. If you'd like to provide feedback anyway, I've just pushed a branch with a large auxillary chapter: https://github.com/erikrose/blessings/blob/blessed-integration-docs-further-reading-and-growing-pains/docs/pains.rst

**Comment by jquast** [comment]
ping

**Comment by jquast** [comment]
ping

**Comment by erikrose** [comment]
Hey, @jquast, you don't have to ask my permission on things. Consider yourself an equal co-maintainer of the project. Just let me know when blessed-integration settles down, and I'll come along and make my contributions. Then we can cut the 1.9 (if backward-compatible) or 2.0 release!

**Comment by erikrose** [comment]
Also, you are to be congratulated. :-) Thomas Ballinger is giving [a session tomorrow about terminal libs](https://us.pycon.org/2015/schedule/presentation/401/), and blessings and blessed are to be prominently featured, along with the good news that they're merging.

**Pull request merged**
